### ISSUE TITLE
Count mismatch

### ISSUE THREAD

**Issue by ddrdushy** [kgashok/elm-simple-json-decoding#21]
Campers in the gitter room is 275. Generated Value is 336 Campers.

**Comment by ddrdushy** [comment]
Campers count changing when i Click the `update from Gitter` button

**Comment by kgashok** [comment]
Good find! Yes that's a bug and I need to fix that!

**Comment by kgashok** [comment]
Fixing `#21` in version `v1.0-beta-21` is purely coincidental! Cheers!
